#!/usr/bin/env python3
# Render the frame captions of dpdk_loopback ("FRAME 07/20", "3840x2160  RFSoC 4x2 UDP loopback")
# once, as 1-bit monospace glyphs, into font.h. Needs Pillow and DejaVu Sans Mono Bold.
#   python3 gen_font.py > font.h
from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
SETS = [("big", 150, "FRAME0123456789/ "), ("small", 60, "".join(chr(c) for c in range(32, 127)))]

print("// Generated by gen_font.py from DejaVu Sans Mono Bold: 1-bit glyphs, rows MSB first.")
print("#include <stdint.h>")
for name, size, chars in SETS:
    font = ImageFont.truetype(TTF, size)
    asc, desc = font.getmetrics()
    adv = round(font.getlength("M"))
    hgt = asc + desc
    rb = (adv + 7) // 8
    print(f"#define FONT_{name.upper()}_W {adv}")
    print(f"#define FONT_{name.upper()}_H {hgt}")
    print(f'static const char font_{name}_chars[] = "{chars.replace(chr(92), chr(92) * 2).replace(chr(34), chr(92) + chr(34))}";')
    print(f"static const uint8_t font_{name}[{len(chars)}][{hgt * rb}] = {{")
    for ch in chars:
        im = Image.new("1", (adv, hgt), 0)
        ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=1)
        px = im.load()
        row = []
        for y in range(hgt):
            for b in range(rb):
                v = 0
                for i in range(8):
                    x = b * 8 + i
                    if x < adv and px[x, y]:
                        v |= 0x80 >> i
                row.append(v)
        print("    {" + ",".join(str(v) for v in row) + "},")
    print("};")
